spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fitness
    username: postgres
    password: secret

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    context-path: /fitness