spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fitness
    username: postgres
    password: ${DB_PASSWORD}

  mail:
    host: smtp.gmail.com
    username: gandalfdude@gmail.com
    password: ${MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        smtps:
          trust: smtp.gmail.com


  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  servlet:
    context-path: /fitness

org:
  jobrunr:
    dashboard:
      enabled: true
      port: 8000
    miscellaneous:
      allow-anonymous-data-usage: false
    jobs:
      retry-back-off-time-seed: 1
    database:
      table-prefix: app.